### ISSUE TITLE
GET param support

### ISSUE THREAD

**Issue by mac-s-g** [mac-s-g/github-help-wanted#11]
users should be able to use GET params in the url to specify desired filters.

http://github-help-wanted.com?languages=["python"]&labels=["help wanted","question"]

(or something similar) should load up the page with relevant filters and results populated

additionally, when a user manipulates filters, the url params should be updated.

**Comment by KhaledSamir** [comment]
@mac-s-g Hi Mac, I'm new here and just wanted to make sure if you already started working on this item or not?

**Comment by mac-s-g** [comment]
@KhaledSamir this one is open.  I'd love to get some help!  and i'm happy to review pr's.

**Comment by KhaledSamir** [comment]
@mac-s-g Sure, let me see if I can fix it by tomorrow. I'll keep you updated!

**Comment by KhaledSamir** [comment]
@mac-s-g it seems we need to use React-Router , do you have any issue if we install it and use within the app?

**Comment by mac-s-g** [comment]
I'm all for that!

**Comment by KhaledSamir** [comment]
@mac-s-g ok, let me read more about it to be familiar more and I'll work on this feature after I come back from the vacation :) ... Happy holiday season for you and for the team!

**Comment by mac-s-g** [comment]
awesome, same to you!  btw: adding react-router will also help with the other feature request (idea/collaboration board) :+1: :santa:

**Comment by KhaledSamir** [comment]
@mac-s-g I'm sorry to say that I really tried to participate in these couple of weeks and dedicate some time to study React well but unfortunately, a lot of things still going on work and my personal life so didn't get any chance to start on this task. Please feel free to start on it and I'll check soon to see if you/someone started on it so I can help as soon as I get a chance.

**Comment by mac-s-g** [comment]
@KhaledSamir no sweat!! [react-router](https://www.npmjs.com/package/react-router) and [react-redux-router](https://www.npmjs.com/package/react-redux-router) definitely come with a learning curve.  I appreciate you reaching out and getting involved.
