### ISSUE TITLE
React Slack Clone

### ISSUE THREAD

**Issue by bookercodes** [mac-s-g/github-help-wanted#17]
Hey, would it be cool if I sent a pull request adding [React Slack Clone](https://github.com/pusher/react-slack-clone)?

We have a handful of "Help Wanted" issues and would love to get people involved: https://github.com/pusher/react-slack-clone/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

**Comment by mac-s-g** [comment]
hey @bookercodes ,

As soon as you add the help wanted label to your issues, they'll show up in the github-help-wanted stream.  I'm basically just querying github's issue search api.
https://github.com/mac-s-g/github-help-wanted/blob/master/src/js/actions/index.js#L65

I found your issues on page three after adding the "good first issue" label 
![react-slack-clone-ghw](https://user-images.githubusercontent.com/4097374/38042029-17fd723a-3268-11e8-834e-49fce008316e.png)

cool looking project by the way!  
thanks for reaching out.
